export const userTypes = {
    HANDLE_LOGIN: 'HANDLE_LOGIN',
    HANDLE_LOGOUT: 'HANDLE_LOGOUT',
    HANDLE_REGISTER: 'HANDLE_REGISTER',
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE'
}